/*
Input keys for ATC simulator

Paul Wilson
30/4/96

*/

// Command language atoms and special keys

# define ESC 27
# define BACKSPACE '\b'
# define F10 68
# define HOME 71
# define UP_ARROW 72
# define PG_UP 73
# define LEFT_ARROW 75
# define RIGHT_ARROW 77
# define END 79
# define DOWN_ARROW 80
# define PG_DN 81
# define RETURN 13

# define K_CHANGE_ALTITUDE 'a'
# define K_TURN 't'
# define K_CIRCLE 'c'
# define K_AIRPORT 'a'
# define K_BEACON 'b'
# define K_CLOCKWISE 'r'
# define K_ASCEND	'c'
# define K_ANTICLOCKWISE 'l'
# define K_DELAY 'a'
# define K_DESCEND 'd'
# define K_GATE 'e'
# define K_TOWARDS 't'
# define K_0 'w'
# define K_45 'e'
# define K_90 'd'
# define K_135 'c'
# define K_180 'x'
# define K_225 'z'
# define K_270 'a'
# define K_315 'q'

